server:
  port: 8761

spring:
  application:
     name: service-discovery

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    renewal-percent-threshold: 0.49

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF